#!/bin/sh

# -----------------------------------------------------------------------------
# AUTHOR      : ZANY (91037677)
# DESCRIPTION : Netty4 Test Server
# ARGUMENTS   : -h, --help
# CREATION    : 2016-01-04
# -----------------------------------------------------------------------------
# Copyright(c) 2015 kt corp. All rights reserved.
# -----------------------------------------------------------------------------

BASEDIR=`cd $(dirname $0); pwd`
BASESYS="$(uname -srv)"

APP_NAME="netty4-test-server"
APP_DESC="Netty4 Test Server"

APP_CONF="$BASEDIR/res/config/application.yml"
LOG_CONF="$BASEDIR/res/config/logback-deploy.xml"
LOG_FILE="$BASEDIR/log/$APP_NAME.log"

CMD_JAVA="$JAVA_HOME/bin/java"

CMD_VM_OPTIONS="-Xms512m -Xmx1024m -XX:PermSize=256m -XX:MaxPermSize=512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Djava.security.egd=file:///dev/urandom"
CMD_EXEC_ARGS="--spring.config.location=$APP_CONF --logging.config=$LOG_CONF --logging.file=$LOG_FILE"
CMD_USER_ARGS="-Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true"

JAR_FILE="$BASEDIR/lib/$APP_NAME-*.jar"

printf "\n$BASESYS"
printf "\n"

if [ "$BASEDIR" != `pwd` ]; then
  printf "\nPlease run this script at it's own directory."
  printf "\n"
  exit 1
fi

if [ ! -d $BASEDIR/tmp ]; then
  mkdir -p $BASEDIR/tmp
fi

if [ ! -d $BASEDIR/log ]; then
  mkdir -p $BASEDIR/log
fi

if [ -f $JAR_FILE ]; then
  $CMD_JAVA -jar $JAR_FILE $@ $CMD_VM_OPTIONS $CMD_EXEC_ARGS $CMD_USER_ARGS
else
  printf "\nExecutable jar file does not exist. ($JAR_FILE)"
fi

printf "\n"
